services:
  rsyslog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rsyslox-test
    ports:
      - "8000:8000"
    volumes:
      - ../build:/host-build:ro
      - ../scripts:/host-scripts:ro
    environment:
      - TZ=Europe/Berlin
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_NAME=Syslog
      - DB_USER=rsyslog
      - DB_PASS=password
      - SERVER_PORT=8000
    stdin_open: true
    tty: true
